# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cats_vs_dogs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63\x61ts_vs_dogs.proto\x12\x0c\x63\x61ts_vs_dogs\"\"\n\x11\x43\x61tsVsDogsRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"!\n\x12\x43\x61tsVsDogsResponse\x12\x0b\n\x03\x63ls\x18\x01 \x01(\t2\xd8\x01\n\x11\x43\x61tsVsDogsService\x12\x62\n\x1d\x43\x61tsVsDogsTensorflowInference\x12\x1f.cats_vs_dogs.CatsVsDogsRequest\x1a .cats_vs_dogs.CatsVsDogsResponse\x12_\n\x1a\x43\x61tsVsDogsPyTorchInference\x12\x1f.cats_vs_dogs.CatsVsDogsRequest\x1a .cats_vs_dogs.CatsVsDogsResponseb\x06proto3')



_CATSVSDOGSREQUEST = DESCRIPTOR.message_types_by_name['CatsVsDogsRequest']
_CATSVSDOGSRESPONSE = DESCRIPTOR.message_types_by_name['CatsVsDogsResponse']
CatsVsDogsRequest = _reflection.GeneratedProtocolMessageType('CatsVsDogsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATSVSDOGSREQUEST,
  '__module__' : 'cats_vs_dogs_pb2'
  # @@protoc_insertion_point(class_scope:cats_vs_dogs.CatsVsDogsRequest)
  })
_sym_db.RegisterMessage(CatsVsDogsRequest)

CatsVsDogsResponse = _reflection.GeneratedProtocolMessageType('CatsVsDogsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CATSVSDOGSRESPONSE,
  '__module__' : 'cats_vs_dogs_pb2'
  # @@protoc_insertion_point(class_scope:cats_vs_dogs.CatsVsDogsResponse)
  })
_sym_db.RegisterMessage(CatsVsDogsResponse)

_CATSVSDOGSSERVICE = DESCRIPTOR.services_by_name['CatsVsDogsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATSVSDOGSREQUEST._serialized_start=36
  _CATSVSDOGSREQUEST._serialized_end=70
  _CATSVSDOGSRESPONSE._serialized_start=72
  _CATSVSDOGSRESPONSE._serialized_end=105
  _CATSVSDOGSSERVICE._serialized_start=108
  _CATSVSDOGSSERVICE._serialized_end=324
# @@protoc_insertion_point(module_scope)
